(function offers() {
    window.__ll_offers = [
        {
            "id": 5,
            "title": "Credit7",
            "code": "",
            "link": "https://keitaro.sypchenko.me/5kB68Y",
            "credit_first": "500-7000",
            "credit_time": "5-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.99,
            "logo": "credit7.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 2,
            "day_offer": 0,
            "st": 1,
            "image": "/images/credit7.png"
        },
        {
            "id": 6,
            "title": "Dinero",
            "code": "",
            "link": "https://keitaro.sypchenko.me/BBpmws",
            "credit_first": "300-15000",
            "credit_time": "7-45",
            "rate_from": 0.00,
            "arp": 0.00,
            "rating": 4.83,
            "logo": "/images/dinero.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 18,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 7,
            "title": "CreditKasa",
            "code": "",
            "link": "https://keitaro.sypchenko.me/Ty8NGD",
            "credit_first": "400-10000",
            "credit_time": "1-27",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.97,
            "logo": "/images/creditkasa.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 4,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 10,
            "title": "Moneyveo",
            "code": "",
            "link": "https://keitaro.sypchenko.me/M89tn4",
            "credit_first": "100-15000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.92,
            "logo": "/images/moneyveo.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 9,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 11,
            "title": "CCloan",
            "code": "",
            "link": "https://keitaro.sypchenko.me/jMgGdx",
            "credit_first": "400-15000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.86,
            "logo": "/images/ccloan.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 15,
            "day_offer": 1,
            "st": 1
        },
        {
            "id": 12,
            "title": "ШвидкоГрошi",
            "code": "",
            "link": "https://keitaro.sypchenko.me/ngHG3G",
            "credit_first": "600-10000",
            "credit_time": "1-14",
            "rate_from": 2.00,
            "arp": 0.00,
            "rating": 4.94,
            "logo": "/images/shvydkogroshi.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 7,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 13,
            "title": "E-Cash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/QpDnJx",
            "credit_first": "500-8000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.78,
            "logo": "/images/e-cash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 23,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 15,
            "title": "MyCredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/sN7vMw",
            "credit_first": "100-6000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.84,
            "logo": "/images/mycredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 17,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 17,
            "title": "Miloan",
            "code": "",
            "link": "https://keitaro.sypchenko.me/J4bJvx",
            "credit_first": "500-12000",
            "credit_time": "1-30",
            "rate_from": 0.00,
            "arp": 0.00,
            "rating": 4.85,
            "logo": "/images/miloan.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 16,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 18,
            "title": "CreditPlus",
            "code": "",
            "link": "https://keitaro.sypchenko.me/gcwtHs",
            "credit_first": "500-10000",
            "credit_time": "3-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.91,
            "logo": "/images/credit-plus.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 10,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 19,
            "title": "AlexCredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/D4YKzx",
            "credit_first": "100-3000",
            "credit_time": "5-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.90,
            "logo": "/images/alexcredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 11,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 23,
            "title": "CashBerry",
            "code": "",
            "link": "https://keitaro.sypchenko.me/HJbWJB",
            "credit_first": "500-5000",
            "credit_time": "7-30",
            "rate_from": 1.50,
            "arp": 0.00,
            "rating": 4.93,
            "logo": "/images/cashberry.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 8,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 25,
            "title": "BestCredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/c8kxjq",
            "credit_first": "1000-10000",
            "credit_time": "5-30",
            "rate_from": 1.90,
            "arp": 0.00,
            "rating": 4.50,
            "logo": "/images/bestcredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 52,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 26,
            "title": "Cashinsky",
            "code": "",
            "link": "https://keitaro.sypchenko.me/g2sxLR",
            "credit_first": "800-5000",
            "credit_time": "5-30",
            "rate_from": 1.91,
            "arp": 0.00,
            "rating": 4.95,
            "logo": "/images/cashinsky.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 6,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 27,
            "title": "CashUp",
            "code": "",
            "link": "https://keitaro.sypchenko.me/dDTMKd",
            "credit_first": "250-8000",
            "credit_time": "1-30",
            "rate_from": 1.50,
            "arp": 0.00,
            "rating": 4.63,
            "logo": "/images/cashup.jpeg",
            "feature_color": "",
            "feature_text": "",
            "pos": 39,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 28,
            "title": "Credit365",
            "code": "",
            "link": "https://keitaro.sypchenko.me/rQ5qMN",
            "credit_first": "500-20000",
            "credit_time": "7-30",
            "rate_from": 0.70,
            "arp": 0.00,
            "rating": 4.68,
            "logo": "/images/credit365.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 32,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 29,
            "title": "CreditCash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/Kf8ng8",
            "credit_first": "1000-100000",
            "credit_time": "180-1800",
            "rate_from": 1.80,
            "arp": 0.00,
            "rating": 4.51,
            "logo": "/images/creditcash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 51,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 30,
            "title": "CreditLite",
            "code": "",
            "link": "https://keitaro.sypchenko.me/LBxz8c",
            "credit_first": "1000-5000",
            "credit_time": "3-30",
            "rate_from": 1.75,
            "arp": 0.00,
            "rating": 4.52,
            "logo": "/images/creditlite.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 50,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 31,
            "title": "CreditOn",
            "code": "",
            "link": "https://keitaro.sypchenko.me/qqfqvL",
            "credit_first": "500-10000",
            "credit_time": "1-28",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.77,
            "logo": "/images/crediton.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 24,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 32,
            "title": "CreditUP",
            "code": "",
            "link": "https://keitaro.sypchenko.me/XQHs38",
            "credit_first": "1000-8000",
            "credit_time": "3-30",
            "rate_from": 1.90,
            "arp": 0.00,
            "rating": 4.50,
            "logo": "/images/creditup.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 53,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 33,
            "title": "Forza24",
            "code": "",
            "link": "https://keitaro.sypchenko.me/g34w98",
            "credit_first": "1000-4000",
            "credit_time": "65-365",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.76,
            "logo": "/images/forza24.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 25,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 34,
            "title": "ForzaCredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/FqhRw8",
            "credit_first": "1000-15000",
            "credit_time": "1-10",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.75,
            "logo": "/images/forzacredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 25,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 35,
            "title": "Gofingo",
            "code": "",
            "link": "https://keitaro.sypchenko.me/YnC2wG",
            "credit_first": "500-10000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.89,
            "logo": "/images/gofingo.jpg",
            "feature_color": "",
            "feature_text": "",
            "pos": 12,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 36,
            "title": "iKapusta",
            "code": "",
            "link": "https://keitaro.sypchenko.me/sC8hpZ",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.74,
            "logo": "/images/ikapusta.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 26,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 37,
            "title": "KF.UA",
            "code": "",
            "link": "https://keitaro.sypchenko.me/jn7q6c",
            "credit_first": "1000-4000",
            "credit_time": "5-180",
            "rate_from": 2.00,
            "arp": 0.00,
            "rating": 4.50,
            "logo": "/images/kfua.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 54,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 38,
            "title": "KLT Credit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/BLRmVQ",
            "credit_first": "1000-10000",
            "credit_time": "7-30",
            "rate_from": 1.65,
            "arp": 0.00,
            "rating": 4.53,
            "logo": "/images/kltcredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 49,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 39,
            "title": "Loany",
            "code": "",
            "link": "https://keitaro.sypchenko.me/njP6dh",
            "credit_first": "1000-8000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.73,
            "logo": "/images/loany.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 27,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 40,
            "title": "MegaGroshi",
            "code": "",
            "link": "https://keitaro.sypchenko.me/8bXPfK",
            "credit_first": "500-15000",
            "credit_time": "7-27",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.72,
            "logo": "/images/megagroshi.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 28,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 41,
            "title": "Microcash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/WBtbVH",
            "credit_first": "300-4000",
            "credit_time": "3-30",
            "rate_from": 1.70,
            "arp": 0.00,
            "rating": 4.60,
            "logo": "/images/microcash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 42,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 42,
            "title": "MisterMoney",
            "code": "",
            "link": "https://keitaro.sypchenko.me/p641Tn",
            "credit_first": "100-5000",
            "credit_time": "1-30",
            "rate_from": 1.30,
            "arp": 0.00,
            "rating": 4.62,
            "logo": "/images/mistermoney.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 40,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 43,
            "title": "Monetka",
            "code": "",
            "link": "https://keitaro.sypchenko.me/rsjt9y",
            "credit_first": "1000-3000",
            "credit_time": "3-30",
            "rate_from": 1.20,
            "arp": 0.00,
            "rating": 4.67,
            "logo": "/images/monetka.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 33,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 44,
            "title": "Money4YOU",
            "code": "",
            "link": "https://keitaro.sypchenko.me/2xmk8p",
            "credit_first": "500-3000",
            "credit_time": "2-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.71,
            "logo": "/images/money4you.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 29,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 45,
            "title": "MoneyBOOM",
            "code": "",
            "link": "https://keitaro.sypchenko.me/22ydxQ",
            "credit_first": "250-4000",
            "credit_time": "5-65",
            "rate_from": 1.75,
            "arp": 0.00,
            "rating": 4.59,
            "logo": "/images/moneyboom.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 43,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 46,
            "title": "MyWallet",
            "code": "",
            "link": "https://keitaro.sypchenko.me/wHmdn3",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 1.60,
            "arp": 0.00,
            "rating": 4.61,
            "logo": "/images/mywallet.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 41,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 47,
            "title": "Pozichka",
            "code": "",
            "link": "https://keitaro.sypchenko.me/4XLr84",
            "credit_first": "250-4000",
            "credit_time": "5-65",
            "rate_from": 1.75,
            "arp": 0.00,
            "rating": 4.58,
            "logo": "/images/pozichka.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 44,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 48,
            "title": "Slon Credit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/vz4BQX",
            "credit_first": "5000-50000",
            "credit_time": "90-365",
            "rate_from": 0.54,
            "arp": 0.00,
            "rating": 4.66,
            "logo": "/images/sloncredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 34,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 49,
            "title": "SOSCredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/ggNGyy",
            "credit_first": "500-5000",
            "credit_time": "1-30",
            "rate_from": 1.00,
            "arp": 0.00,
            "rating": 4.65,
            "logo": "/images/soscredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 35,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 50,
            "title": "StudentLoan",
            "code": "",
            "link": "https://keitaro.sypchenko.me/Q8q21c",
            "credit_first": "300-10000",
            "credit_time": "5-30",
            "rate_from": 0.00,
            "arp": 0.00,
            "rating": 4.79,
            "logo": "/images/studentloan.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 22,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 51,
            "title": "Swizo",
            "code": "",
            "link": "https://keitaro.sypchenko.me/kbBngx",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.70,
            "logo": "/images/swizo.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 30,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 52,
            "title": "TopCash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/QcpTH6",
            "credit_first": "500-10000",
            "credit_time": "1-30",
            "rate_from": 1.00,
            "arp": 0.00,
            "rating": 4.66,
            "logo": "/images/topcash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 36,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 53,
            "title": "UltraCash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/6PNcrp",
            "credit_first": "500-4000",
            "credit_time": "1-30",
            "rate_from": 1.00,
            "arp": 0.00,
            "rating": 4.65,
            "logo": "/images/ultracash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 37,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 54,
            "title": "Verocash",
            "code": "",
            "link": "https://keitaro.sypchenko.me/MYtghW",
            "credit_first": "500-5000",
            "credit_time": "7-30",
            "rate_from": 1.49,
            "arp": 0.00,
            "rating": 4.64,
            "logo": "/images/verocash.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 38,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 55,
            "title": "Zecredit",
            "code": "",
            "link": "https://keitaro.sypchenko.me/82qyns",
            "credit_first": "1000-7000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.81,
            "logo": "/images/zecredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 20,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 56,
            "title": "БыстроЗайм",
            "code": "",
            "link": "https://keitaro.sypchenko.me/hVQxWR",
            "credit_first": "500-15000",
            "credit_time": "7-30",
            "rate_from": 0.00,
            "arp": 0.00,
            "rating": 4.87,
            "logo": "/images/bistrozaim.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 14,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 57,
            "title": "Ваша Готiвочка",
            "code": "",
            "link": "https://keitaro.sypchenko.me/3mTj3c",
            "credit_first": "200-7000",
            "credit_time": "1-16",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.96,
            "logo": "/images/vashagotivochka.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 5,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 58,
            "title": "ГлобалКредит",
            "code": "",
            "link": "https://keitaro.sypchenko.me/99DCcr",
            "credit_first": "200-5000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.88,
            "logo": "/images/globalcredit.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 13,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 59,
            "title": "Грошi Всiм",
            "code": "",
            "link": "https://keitaro.sypchenko.me/gFgNqz",
            "credit_first": "500-15000",
            "credit_time": "5-30",
            "rate_from": 1.90,
            "arp": 0.00,
            "rating": 4.50,
            "logo": "/images/groshivsim.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 55,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 60,
            "title": "Грошик",
            "code": "",
            "link": "https://keitaro.sypchenko.me/47q9bW",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 1.70,
            "arp": 0.00,
            "rating": 4.54,
            "logo": "/images/groshik.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 48,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 61,
            "title": "ЕвроГрошi",
            "code": "",
            "link": "https://keitaro.sypchenko.me/4sYbSs",
            "credit_first": "1000-10000",
            "credit_time": "1-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.82,
            "logo": "/images/eurogroshi.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 19,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 62,
            "title": "КачайГрошi!",
            "code": "",
            "link": "https://keitaro.sypchenko.me/RT45Xt",
            "credit_first": "500-10000",
            "credit_time": "5-30",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.80,
            "logo": "/images/kachaygroshi.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 21,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 63,
            "title": "КошельОК",
            "code": "",
            "link": "https://keitaro.sypchenko.me/wP9KHw",
            "credit_first": "500-15000",
            "credit_time": "7-65",
            "rate_from": 0.01,
            "arp": 0.00,
            "rating": 4.69,
            "logo": "/images/koshelok.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 31,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 64,
            "title": "КредитКафе",
            "code": "",
            "link": "https://keitaro.sypchenko.me/dvxXMM",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 1.70,
            "arp": 0.00,
            "rating": 4.57,
            "logo": "/images/kreditkafe.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 45,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 65,
            "title": "Новi Кредити",
            "code": "",
            "link": "https://keitaro.sypchenko.me/CPnH6s",
            "credit_first": "500-5000",
            "credit_time": "5-30",
            "rate_from": 1.80,
            "arp": 0.00,
            "rating": 4.56,
            "logo": "/images/novikredity.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 46,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 66,
            "title": "ПростоГрошi",
            "code": "",
            "link": "https://keitaro.sypchenko.me/3kTWj2",
            "credit_first": "600-5000",
            "credit_time": "3-28",
            "rate_from": 2.00,
            "arp": 0.00,
            "rating": 4.55,
            "logo": "/images/prostogroshi.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 47,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 67,
            "title": "На Все",
            "code": "",
            "link": "https://keitaro.sypchenko.me/N7BhQ8",
            "credit_first": "5000-20000",
            "credit_time": "1-70",
            "rate_from": 1.00,
            "arp": 0.00,
            "rating": 5.00,
            "logo": "/images/navse.png",
            "feature_color": "",
            "feature_text": "",
            "pos": 1,
            "day_offer": 0,
            "st": 1
        },
        {
            "id": 68,
            "title": "УкрПозика",
            "code": "",
            "link": "https://keitaro.sypchenko.me/QfXjC9",
            "credit_first": "300-15000",
            "credit_time": "7-30",
            "rate_from": 0.00,
            "arp": 0.00,
            "rating": 4.98,
            "logo": "/images/ukrpozyka.png",
            "feature_color": "",
            "feature_text": "Отдаете меньше, чем берете",
            "pos": 3,
            "day_offer": 0,
            "st": 1
        }
    ];
})();
